# Generated by Django 4.1.5 on 2023-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuvas',
            name='data',
            field=models.CharField(max_length=20),
        ),
    ]
